backend = "kmeans"
color_space = "labmixed"
threshold = 11
palette = "dark16"

[templates]
cava.template = 'colors-cava'
cava.target = '~/.config/cava/config'

hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/hypr/colors.conf'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/colors.rasi'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors.css'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/colors.conf'

#swaync.template = 'colors-swaync.css'
#swaync.target = '~/.config/swaync/wallust/colors-wallust.css'

#macchina.template = 'colors-macchina.toml'
#macchina.target = '~/.config/macchina/themes/wallust.toml'

#wezterm.template = 'colors-wezterm.toml'
#wezterm.target = '~/.config/wezterm/colors/wallust.toml'

#zathura.template = 'colors-zathura'
#zathura.target = '~/.config/zathura/zathurarc'
